#!/bin/sh

# subst:

# first make a file where we can perform a substitution:
cat > tmp1.py <<EOF
# some comment
def f(x):
    return 2

compute_formula1(x, y, z)
if not first:
    compute_formula2(a, b)
EOF

scitools subst 'compute_(.+?)\(' 'calculate_\g<1>(' tmp1.py


# file2interactive:
cat > tmp2.py <<EOF
import os
origdir = os.getcwd()
os.chdir(os.pardir)
os.getcwd()
origdir
EOF

scitools file2interactive tmp2.py
