#!/usr/bin/env python
# update all modules (run preprocessor etc.)
import os, shutil

ppy_warning = """\
#############################################################################
# WARNING: This is an autogenerated file!! Do not edit this file!!
# Edit the original file %s (on which preprocess.py will be run)
#############################################################################
"""

def run_preprocess(files):
    tempfile = 'tmpp.py'
    for f in files:
        f_root, f_ext = os.path.splitext(f)
        if f_ext == '.ppy':
            shutil.copy(f, tempfile)
            f_new = f_root + '.py'
            cmd = 'preprocess %s > %s' % (tempfile, f_new)
            failure = os.system(cmd)
            if failure:
                raise OSError, 'Could not run command\n%s' % cmd
            else:
                print 'preprocess %s -> %s' % (f, f_new)
            # add warning header:
            _f = open(f_new, 'r'); _str = _f.read(); _f.close()
            _warning = ppy_warning % f
            _f = open(f_new, 'w'); _f.write(_warning + _str); _f.close()

if __name__ == '__main__':
    files = ['numpytools.ppy',]
    run_preprocess(files)

